# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-03 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ambientalweb', '0002_company_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('quantity', models.FloatField(verbose_name='Quantidade')),
            ],
            options={
                'verbose_name': 'Coleta',
            },
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('quantity', models.FloatField(verbose_name='Quantidade')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambientalweb.Company', verbose_name='Parceiro')),
            ],
            options={
                'verbose_name': 'Venda',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Data/hora de sa\xedda')),
                ('end_date', models.DateTimeField(verbose_name='Data/hora de chegada')),
                ('distance_travelled', models.FloatField(verbose_name='Deslocamento')),
            ],
            options={
                'verbose_name': 'Deslocamento',
            },
        ),
        migrations.CreateModel(
            name='Unity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nome')),
                ('abreviation', models.CharField(max_length=10, verbose_name='Abrevia\xe7\xe3o')),
            ],
            options={
                'verbose_name': 'Unidade de medida',
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='distance_unity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambientalweb.Unity', verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='sell',
            name='sell_unity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambientalweb.Unity', verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='sell',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambientalweb.Trip', verbose_name='Deslocamento'),
        ),
        migrations.AddField(
            model_name='collect',
            name='collect_unity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambientalweb.Unity', verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='collect',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambientalweb.Company', verbose_name='Parceiro'),
        ),
        migrations.AddField(
            model_name='collect',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambientalweb.Trip', verbose_name='Deslocamento'),
        ),
    ]
